name: 防控疫情打卡（防止漏打）

on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 15 * * *'

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Chrome and ChromeDriver
        run: bash install_chrome.sh
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Report
        run: python main.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
